org: ebal5
console: true
service: serverless-bolt-js
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-offline
provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs16.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/slackTable'

functions:
  ordinary:
    handler: dist/index.handler
    url: true
  installation:
    handler: dist/installation.handler
    url: true

resources:
  Resources:
    slackTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: slackTable
        AttributeDefinitions:
          - AttributeName: teamId
            AttributeType: S
        KeySchema:
          - AttributeName: teamId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
